image: elixir:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: $POSTGRES_TEST_DB
  POSTGRES_HOST: postgres
  POSTGRES_USER: $POSTGRES_TEST_USER
  POSTGRES_PASSWORD: "$POSTGRES_TEST_PASSWORD"
  MIX_ENV: "test"

cache:
  key:
    files:
      - mix.lock
  paths:
    - deps
    - _build
    - ~/.mix

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get --only test
  - mix ecto.setup

mix:
  cache:
    policy: pull
  script:
    - mix credo --strict
    - mix format --check-formatted
    - mix coveralls
