image: elixir:latest

stages:
  - test
  - deploy

test:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: $POSTGRES_TEST_DB
    POSTGRES_HOST: postgres
    POSTGRES_USER: $POSTGRES_TEST_USER
    POSTGRES_PASSWORD: "$POSTGRES_TEST_PASSWORD"
    MIX_ENV: "test"
  script:
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get --only test
    - mix ecto.setup
    - mix credo --strict
    - mix format --check-formatted
    - mix coveralls
  only:
    - develop
    - master
    - merge_requests

deploy:
  stage: deploy
  script:
    - git remote add gigalixir $GIGALIXIR_REMOTE_URL
    - git push -f gigalixir HEAD:refs/heads/master
  only:
    - master